#=========================使用p6spy驱动监控SQL性能分析
#server:
#  port: 9999
spring:
  profiles: dev
  datasource:
    username: root
    password: root
    url: jdbc:p6spy:mysql://localhost:3306/imooc2?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    filters: stat,wall